### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by johntk** [m-abboud/InspectionKeyBinder-IntelliJPlugin#1]
Plugin seems to have stopped working

`com.intellij.codeInspection.InspectionProfile.getModifiableModel()Lcom/intellij/codeInspection/ModifiableModel;
java.lang.NoSuchMethodError: com.intellij.codeInspection.InspectionProfile.getModifiableModel()Lcom/intellij/codeInspection/ModifiableModel;
	at com.othoslabs.InspectionToggler.modifyAndCommitProjectProfile(InspectionToggler.java:46)
	at com.othoslabs.InspectionToggler.toggleInspection(InspectionToggler.java:25)
	at com.othoslabs.actions.SpellCheckToggleAction.actionPerformed(SpellCheckToggleAction.java:25)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inSecondStrokeInProgressState(IdeKeyEventDispatcher.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inWaitForSecondStrokeState(IdeKeyEventDispatcher.java:292)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by m-abboud** [comment]
fixed now. API changed a tad in 2017.1 version...

**Comment by m-abboud** [comment]
and updated compiled jar can be found here: https://mabboud.net/file-uploads/InspectionKeyBinder-1.1.jar
